### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by miltonvincenttis**

### CODE REVIEW

**Comment by miltonvincenttis** [comment]
Pode fazer o merge.

**Review by miltonvincenttis — COMMENTED** [review]
Tudo Ok

**Comment by miltonvincenttis** [comment]
Ok

**Review by miltonvincenttis — COMMENTED** [review]
it seams everything ok.

**Comment by miltonvincenttis** [comment]
Ok

**Review by oss-covid19 — APPROVED** [review]

**Pull request merged**
